### PR TITLE
Social Media ~ Milestone 1 : Docs

### PR DESCRIPTION
**Pull request by o-rashad**
- Entity Relationship Diagram file has been added to the README file.

### CODE REVIEW

**Review by carlos-ssh — APPROVED** [review]
**Status: Approved!** 🍾👏🏽
Hello Team, your diagram and README file looks great.
_You can merge and continue working!_

_Happy Coding!_ 👾
@carlos-ssh

**Comment by o-rashad** [comment]
Thank you @carlos-ssh for the review.

**Review by oloomoses — COMMENTED** [review]
- You should have a new pull request for each milestone as per the requirements. Kindly create a new pr for Milestone: friendships v1 to avoid milestone reviews in one pull request.
**For the above reason, I will mark this pr as invalid for the Milestone: friendships v1**
- Please make the necessary adjustments and submit for another review

_Slack: Oloo Moses_

**Comment by o-rashad** [comment]
Thanks, @oloomoses for the review, it has to be some sort of misunderstanding, 🤔
we already finished the 1st milestone, as you can see from the last reviewer. 
and there is no 2nd pull request created.
 
yet when we finish the 2nd m.s we will request a new review.

Thanks again :), have a great weekend

**Pull request merged**
