### PR TITLE
Social Media ~ Milestone 3 : friendship v2 #391

### PR DESCRIPTION
**Pull request by o-rashad**
Implemented friendships with 2 rows for mutual friendship.
Friends can add each other now.
   - `Add Friend` button is only available for non-friends.

### CODE REVIEW

**Review by bini-i — CHANGES_REQUESTED** [review]
# Status: Invalid :red_circle:           
### Hello @tanzila-abedin and @od-c0d3r  :wave: 

You should make sure that your repo looks professional before review. Your GitHub workflows are not configured correctly and GitHub actions are not running. Please take a step back and make sure your linters.yml file matches with [this](https://github.com/microverseinc/linters-config/blob/master/ror/.github/workflows/linters.yml) and Github actions are running. 
#### This Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready!



#### If you have any question feel free to ask within the PR and ping me on slack @Binyam Hailemeskel

### HAPPY CODING :computer: :blush: 

> #### Reviewed by Binyam Hailemeskel (Code Reviewer)
> GitHub: [@bini-i](https://github.com/bini-i) 
> Twitter: [@binyamshewa](https://twitter.com/binyamshewa)
> LinkedIn: [LinkedIn](https://www.linkedin.com/in/binyam-hailemeskel-728048151/)

**Comment by tanzila-abedin** [comment]
Thank you for your kind review. @bini-i 
Workflow action is running and Read.me file is updated as per Microvers's requirements.

**Review by cyonii — CHANGES_REQUESTED** [review]
## STATUS: CHANGES REQUIRED ♻️✍️

### TO HIGHLIGHT
Hello team, great work so far, keep up the energy.

### TO IMPROVE
Kindly pay attention to these issues I have pointed out below and fix them in order to get your project approved.
- [x] when friendship is confirmed, an additional row with reversed user-friend pair is created. Please refer to this [article](https://explainextended.com/2009/03/07/selecting-friends) and this [thread](https://stackoverflow.com/questions/4219979/sql-best-practice-for-a-friendship-table). See the code example below:
```ruby
# Friendship model

def confirm_friend
  self.update_attributes(confirmed: true)
  Friendship.create!(friend_id: self.user_id,
                  user_id: self.friend_id,
                  confirmed: true)
end
```
- [x] Kindly add more unit and integration tests, test all your models.

### NICE TO HAVE
Note these are NOT mandatory changes, which means you don't have to implement them, although I encourage you to.
- [x] Thanks to the reverse friendship created when friendship is confirmed, we can find user friends only by user_id in the friendships table
```ruby
# User model

has_many :confirmed_friendships, -> { where confirmed: true }, class_name: "Friendship"
has_many :friends, through: :confirmed_friendships
```
- [x] `User#pending_friends` can be defined as association with SQL query instead of processing objects in application memory (as the database was created to store and query data it is always more efficient than ruby)
```ruby
# User model

# Users who needs to confirm friendship
has_many :pending_friendships, -> { where confirmed: false }, class_name: "Friendship", foreign_key: "user_id"
has_many :pending_friends, through: :pending_friendships, source: :friend
```
- [x] `User#friend_requests` can be defined as association with SQL query instead of processing objects in application memory (as the database was created to store and query data it is always more efficient than ruby)
```ruby
# User model

# Users who requested to be friends (needed for notifications)
has_many :inverted_friendships, -> { where confirmed: false }, class_name: "Friendship", foreign_key: "friend_id"
has_many :friend_requests, through: :inverted_friendships
```
- [x] In order to get all posts written by a user and their friends, you can use a simple method in the User model (in order to NOT do it with Enumerable)
```ruby
# User model

def friends_and_own_posts
  Post.where(user: (self.friends.to_a << self))
  # This will produce SQL query with IN. Something like: select * from posts where user_id IN (1,45,874,43);
end
```

Happy coding, Good luck!
> #### <br>You can ping me on Slack @[CY Kalu](https://microverse-students.slack.com/team/U01494U96FR) to draw my attention in case I do not respond quickly on here. I'm always available and will be glad to help.<br><br>

**Review by elisha2kyakpo1 — APPROVED** [review]
# Status: Approved🎉🎉✔

**Congratulations! You have done a good job making the changes requested**
You can merge and move to the next milestone.

<hr>
**OPTIONAL**
I strongly urge you to add the optional changes the previous reviewer mentioned.

Happy coding
Elisha kyakopo

**Comment by o-rashad** [comment]
Thank you @cyonii @elisha2kyakpo1, for the reviews. 🌟🌟

About mentioning the Optional changes...
It's really hard to focus on any EXTRA requirements
while MV putting the September Deadline on 1.0 Students' heads. 😅

However, surely we would give it a try in any free time if occurred.

**Pull request merged**
