### PR TITLE
Social media website - Milestone: friendships v1

### PR DESCRIPTION
**Pull request by tanzila-abedin**
Created a model with associations and all requested features for friendships along with unit tests.

### CODE REVIEW

**Review by taiwo2 — CHANGES_REQUESTED** [review]
# STATUS : CHANGES REQUIRED ♻️ 
@od-c0d3r, Weldone guy, your app works fine, However here are few changes required 
- [x] User can invite friends ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/send_invitation.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [x] User can see friendships requests ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/pending_request.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [x] User has to accept friendship request to start friendship ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/accept_reject_friendship.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [x] User can reject a friendship request ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/accept_reject_friendship.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [x] There is a button to invite user to friendship on users list page and on single user page ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/user_can_see_invite_buttton.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [x] Posts timeline includes posts written by logged-in user and their friends ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [x] Kindly Add more  Unit and Integration tests!

**Comment by o-rashad** [comment]
Thank you @taiwo2 for the review ⭐️⭐️⭐️, 
We are working on the changes,
and gonna update ASAP.

**Review by cyonii — CHANGES_REQUESTED** [review]
### STATUS: CHANGES REQUIRED ♻️✍️

#### TO HIGHLIGHT
You have shown a great effort since the last review. Well done.

#### TO IMPROVE
You have done a great job so far, but these few issues below still need to be fixed before your project can be approved.
- [x] Posts timeline should include posts written by logged-in user and their friends ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/)), right now I can't see my friends' posts, please fix this.
- [x] One of your tests is failing, kindly make sure all your tests pass.


#### NICE TO HAVE
Note these are not mandatory requirements which means you're not obliged to implement them, although I greatly recommend that you do.
- [x] The receiver of a friendship request can still send a friendship request back to the same User that has already invited them for friendship. You would agree it's pointless to send a friendship request to someone if we're already friends, or if they already invited me for a friendship. It would be nice if you hide the invite button if friendship exists between the users already.

#### <br>You can ping me on Slack @[CY Kalu](https://microverse-students.slack.com/team/U01494U96FR) to draw my attention in case I do not respond quickly on here. I'm always available and will be glad to help.<br><br>

**Comment by o-rashad** [comment]
Thank you @cyonii for the review,
gonna work on the changes and submit ASAP.

**Review by umararshadbut — APPROVED** [review]
# **Status: PROJECT APPROVED** :champagne:
Excellent job on this project guys. :fireworks: Keep it up.
##
**All the required tasks have been fulfilled in this project. I will go ahead and mark this as complete.**
- Congratulations on the splendid job ! :+1: 
- I wish you all the very best in your next tasks :1st_place_medal:
##
Before merge please implement the following suggestions:
- [ ] **[OPTIONAL]** You should not display the invite button for users who are already friends in the ALL USERS view
- [x] **[OPTIONAL]**Consider NOT displaying the currently logged-in user in the ALL USERS view
##
HAPPY CODING :computer:
**Umair**

**Comment by o-rashad** [comment]
Thank you @umararshadbut for the review, 
Definitely will implement your
Suggested changes next.

**Pull request merged**
